stages:
  - install_depos
  - start

cache:
  paths:
    - node_modules/
    - dist/

install_deps:
  stage: install_deps
  script:
    - echo "npm install..."
    - npm install

start:
  stage: start
  script:
    - echo "npm start..."
    - npm start